before_install:
  - gem install bundler

cache: bundler

notifications:
  email: false

rvm:
 - 2.0
 - 2.1

gemfile:
  - Gemfile
  - gemfiles/rails-3-2-stable.gemfile
  - gemfiles/rails-4-0-stable.gemfile
  - gemfiles/rails-4-1-stable.gemfile

before_script:
  - psql -c 'create database carrierwave_test;' -U postgres

addons:
  postgresql: "9.3"
